Bumped rust-version to 1.65 because of this error
error: package `tracing-core v0.1.34` cannot be built because it requires rustc 1.65.0 or newer, while the currently active rustc version is 1.64.0